### ISSUE TITLE
Does not work anymore on 3.4.2

### ISSUE THREAD

**Issue by x-itec** [dkd/plantuml#11]
If I try to view a saved diagram (=saving text in a wiki to see the results), the following error occours:

undefined method `+' for nil:NilClass

Environment:
  Redmine version                3.4.2.stable

**Comment by ncreuschling** [comment]
This is fixed in `v0.5.1`. Thanks for bringing this to our attention.

**Comment by x-itec** [comment]
Hi, seems to be the problem is still not solved, checked out latest version, I have no error message but a long numbercode on the screen (looks like a filename or so in hex).

**Comment by ncreuschling** [comment]
We will have another look at it. Just to be clear: it worked for you before and now it does not anymore.

**Comment by x-itec** [comment]
Wir können gerne mal Teamviewer machen, ich schau mir noch mal die Logs an, vielleicht finde ich noch was. Der Zahlencode wurde als Grafik gerendert (sieht wie ein Hex-Filename aus).

**Comment by ncreuschling** [comment]
Wenn der Code `!include`- oder `!includeurl`-Makros enthält, dann müssen diese erst in den Plugin-Einstellungen erlaubt werden. Tritt das Problem bei allen Codes auf (auch bei einfachen wie `Bob -> Alice : hello`) oder nur ein paar? Hat es denn vorher schon mal funktioniert?

Wäre es möglich, den PlantUML-Code hier zu dokumentieren?

**Comment by telehan** [comment]
same problem reproduce in redmine 3.2.1
pu file can be generated under /redmine/files directory, png file can not generated by convert command in plugins/plantuml/app/controllers/plantuml_controller.rb:7
it report: lib/redmine/sudo_mode.rb:63:in `sudo_mode'
by the way, png can be generate manually with pre-defined /usr/bin/plantuml script

**Comment by ncreuschling** [comment]
Paging @zlorfi
