### ISSUE TITLE
Error executing the plantuml macro "No such file or directory" on Debian system

### ISSUE THREAD

**Issue by sgargel** [dkd/plantuml#14]
The plugin does not work "out of the box" on debian system because of [Differences from upstream Redmine](https://wiki.debian.org/redmine#Differences_from_upstream_Redmine)

Error given is: 

`Error executing the plantuml macro (No such file or directory @ rb_sysopen - /usr/share/redmine/files/plantuml_[...].pu)`

Solution is:

`ln -s /var/lib/redmine/default/files/ /usr/share/redmine/files`

**Comment by ncreuschling** [comment]
Thank you for your comment. I leave it for others to find.
