### ISSUE TITLE
split diagram doesn't work fully

### ISSUE THREAD

**Issue by pdefert** [dkd/plantuml#16]
in this case [http://plantuml.com/sequence-diagram#Splitting_diagrams](http://plantuml.com/sequence-diagram#Splitting_diagrams)
{{plantuml(png)
Alice -> Bob : message 1
Alice -> Bob : message 2

newpage

Alice -> Bob : message 3
Alice -> Bob : message 4

newpage A title for the\nlast page

Alice -> Bob : message 5
Alice -> Bob : message 6

 }}

the plugin include the first schema only. the 2 others are generated on disk but not included in the issue

best regards

**Comment by ncreuschling** [comment]
This is somewhat out of scope.
