### ISSUE TITLE
case using context path, image path is invalid

### ISSUE THREAD

**Issue by hodorii** [dkd/plantuml#17]
I am using context  : http://localhost/redmine

## 1. configuration sub context
insert to first line in "config/environment.rb"
`RedmineApp::Application.routes.default_scope = "/redmine"' 

### /plantuml/png/...
`http://0.0.0.0:3000/plantuml/png/plantuml_ad9c6acbbe4968b81647d194931ab53e6a7598870096bc62e3decbcf34ddd2a8.png
`

### /redmine/plantuml/png/...
`http://0.0.0.0:3000/redmine/plantuml/png/plantuml_ad9c6acbbe4968b81647d194931ab53e6a7598870096bc62e3decbcf34ddd2a8.png`

**Comment by ncreuschling** [comment]
You can change the image path in `init.rb`:

```ruby
macro :plantuml do |obj, args, text|
  # …
  image_tag "/plantuml/#{frmt[:type]}/#{image}#{frmt[:ext]}" # <–
end
