### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by kevinpattison** [dkd/plantuml#18]
I've installed Java on the ubuntu redmine server, plug-in installed in correct plug-in dir, /usr/bin/plantuml file created and given execute permissions and redmine rake command ran:

```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
Migrating plantuml (PlantUML plugin for Redmine)...
...
...
...
```
but plug-in not appearing in plug-in list and path in the readme file gives a 404 and in fact there is no *.jar file in the downloaded plug-in dir.

**Comment by simeonfelis** [comment]
me too, I'm running redmine 3.4.x on postgres. no "plugin_plantuml" in the settings table...

**Comment by simeonfelis** [comment]
I copied the plugin to plugins/plantuml,
ran 
bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=plantuml
as user redmine. I also restarted apached.
But browsing settings/plugin/plantuml will give me a 404.

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  plantuml                       0.5.1
  redmine_agile                  1.4.5
  redmine_bootstrap_kit          0.2.5
  redmine_checklists             3.1.5
  redmine_contacts               4.1.1
  redmine_contacts_helpdesk      3.0.9
  redmine_git_hosting            1.2.3
  redmine_login_audit            0.3.1
  redmine_revision_branches      0.3.1
  redmine_sortable_table         0.99.1

**Comment by surfingtomchen** [comment]
me too !!

**Comment by antoninchadima** [comment]
# meetoo

**Comment by antoninchadima** [comment]
sorry, the problem appeared because i forgot to rename the plugin directory to plantuml/
