### ISSUE TITLE
files folder will be poluted with plant_* file when doing preview

### ISSUE THREAD

**Issue by nogo** [dkd/plantuml#2]
Is there a chance to remove non used files ? 
- Maybe give the diagram a name and don't hash the changes.

**Comment by zlorfi** [comment]
I know it's not optimal, but you could use the cleanup task inside a cron job: https://github.com/dkd/plantuml/blob/master/lib/tasks/cleanup.rake

**Comment by nogo** [comment]
yes seems helpful, right now I'm not using redmine anymore, but I will keep it in mind
thanks @zlorfi
