### ISSUE TITLE
https://www.redmine.org/plugins/plantuml needs update

### ISSUE THREAD

**Issue by paulvi** [dkd/plantuml#24]
https://www.redmine.org/plugins/plantuml needs update to show newer version

**Comment by cappuMUC** [comment]
The plugin isn't compatible with Redmine 4.0 at the moment as it uses `alias_method_chain` for code injection which was deprecated in Rails 5.0.
I've made a pull request (#26 ) to get it compatible with the new version of Redmine.

**Comment by ncreuschling** [comment]
Merged #26.
