### ISSUE TITLE
Export uml to html or pdf

### ISSUE THREAD

**Issue by krjukOFF** [dkd/plantuml#4]
I have installed in Redmine 3.1.0 with plantuml on Centos 7
Not working export pdf or html from redmine- wiki.
In redmine->wiki plantuml show works sample:
{{plantuml(png)
  Bob -> Alice : hello
}}

But after export in html page source -> example

<p><img src="/plantuml/png/plantuml_88358e9331985a8ad4ec566b38dfd68a2875ead47b187542e2bea02c670d50ff.png" alt="Plantuml 88358e9331985a8ad4ec566b38dfd68a2875ead47b187542e2bea02c670d50ff" /></p>

The same link in export pdf file.
Not showing pictures.

Best regards Konstantins.

**Comment by zlorfi** [comment]
I'll look into it. See #1 
Maybe I can find a workaround.

**Comment by ncreuschling** [comment]
We have no plans to dig deeper into this issue.
