### ISSUE TITLE
Installation for Windows

### ISSUE THREAD

**Issue by Mikaso** [dkd/plantuml#7]
First of all, thanks for the great plugin!

I would like u to make a case differentiation in the "Installation" section of your readme. 

Please add the following batch script example:

`java -Djava.io.tmpdir=%TEMP% -Djava.awt.headless=true -jar PATH_TO_YOUR_PLANTUML_BINARY/plantuml.jar "%1" "%2" "%3" "%4"`

**Comment by alxRlja** [comment]
Great. I'm pretty new in Redmine and I'm looking for detailed instructions about installing this plugin in Redmine-Bitnami-windows (2008 R2). Should be simple, but I'm confused with the instructions. What name should have the .cmd file with your code?  Where it should be located? (Do I need create the .cmd  in a C:/usr/bin/plantuml folder or should I create a directory  /usr/bin/plantuml inside the plug in Directory?) Any help ? Thank you very much!

**Comment by hgc2002** [comment]
Detailed instructions for Windows:

0.- I suppose you have Java already installed and accesible via PATH environment variable so you can open any CMD box and type:
`java -version`

1.- Install the plugin as usual, that is: download the zip file from git, extract its content and put the main folder under <redmine>plugins folder and restart Redmine. Example:
`C:\aaa_redmine\redmine-3-1-0\plugins\plantuml`

![imagen](https://user-images.githubusercontent.com/364190/30961024-276f1608-a445-11e7-9992-3a8343bc749f.png)

2.- Download plantuml.jar and put it somewhere in your disk. Example: 
`C:\aaa_redmine\redmine-3-1-0\plugins\plantuml\bin`

Note: currently the direct download from plantuml.com is failing. I used version 8059 from here:
`https://jar-download.com/?search_box=plantuml`

3.- Create a plantuml.bat file and put it in your disk. Example:
`C:\aaa_redmine\redmine-3-1-0\plugins\plantuml\bin\plantuml.bat`

Here is the content of the .bat file (example):
`java -Djava.io.tmpdir=%TEMP% -Djava.awt.headless=true -jar C://aaa_redmine//redmine-3-1-0/plugins/plantuml/bin/plantuml.jar "%1" "%2" "%3" "%4"`

4.- Configure the path of your .bat file in the administration page of the plugin. Example:
![imagen](https://user-images.githubusercontent.com/364190/30961289-ff28cbde-a445-11e7-8e79-bd8dcb4b31b9.png)

5.- Now, use it!
![imagen](https://user-images.githubusercontent.com/364190/30961354-2defca26-a446-11e7-87fc-5f95e21be4f7.png)

**Comment by alxRlja** [comment]
@hgc2002 awesome! thank you very much!
