### ISSUE TITLE
Something wrong with assets on redmine 2.6

### ISSUE THREAD

**Issue by RushOnline** [dkd/plantuml#8]
I've just installed this plugin on redmine 3.2 just fine (changing 3.1 with 3.2 in init.rb). But when installing on 2.6 something going wrong:

```
Environment:
  Redmine version                2.6.10.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux-gnu]
  Rails version                  3.2.22.2
  Environment                    production
  Database adapter               PostgreSQL
Redmine plugins:
  plantuml                       0.3.0
```

```
ActionController::RoutingError (No route matches [GET] "/plugin_assets/plantuml/javascripts/plantuml.js"):
```

I've tried:

```
rake assets:clean
rake assets:precompile
rake redmine:plugins
rake redmine:plugins:assets
rake redmine:plugins:migrate
```

Help me please!

**Comment by RushOnline** [comment]
May this issue caused by plugin folder name changed? I've placed plugin as `redmine/plugins/redmine-plantuml-plugin`.

**Comment by zlorfi** [comment]
Hi @RushOnline,

that's correct. This is how Redmine handles assets from within plugins. Rename the folder back to `plantuml` and all should be finde
